[tool.poetry]
name = "snakedwi"
version = "0.1.0"
description = "snakedwi - BIDS app and snakemake workflow for dwi pre-processing"
authors = ["Ali Khan <alik@robarts.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.11"
snakebids = "^0.5.0"
snakemake = "<7.0.0"
pandas = "^1.4.2"
nibabel = "^3.2.2"
numpy = "^1.22.3"
matplotlib = "^3.5.1"
nilearn = "^0.9.0"
PyPDF2 = "^1.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
snakedwi = "snakedwi.run:main"
