singularity_neuroglia: /project/6050199/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif
#singularity_neuroglia: docker://khanlab/neuroglia-core:latest

singularity:
 prepdwi: '/project/6050199/akhanf/singularity/bids-apps/khanlab_prepdwi_latest.sif'

#leave out extension, will grab nii.gz, bval, bvec, json
in_dwi_prefix: '/project/6050199/akhanf/cfmm-bids/data/Peters/tle3T_phase2/bids/sub-{subject}/dwi/sub-{subject}_acq-{acq}_run-{run}_dwi'

dwi_dict:
 run: 
  - '01'
  - '02'
 acq:
  - 'multiband'

subj_dict:
 subject:   
  - '0061'


flags:
 #using avgb0 was default behaviour in prepdwi, but it could be problematic if there is motion in the scan
 #if set to False, will run topup on all the b0s concatenated -- this takes MUCH longer (hours instead of minutes)
 #  TODO: add an option to select best b0 too (hcppipeline has this..)
 use_avgb0_topup: True 

#can use this to override bids participants.tsv - need to implement that override
participants_tsv: /path/to/participants_tsv
