
singularity:
 prepdwi: '/project/6050199/akhanf/singularity/bids-apps/khanlab_prepdwi_latest.sif'  #should use mrtrix3.0 container instead
 ants: '/project/6050199/akhanf/singularity/ants-v2.3.1.sif'
 fsl: '/project/6050199/akhanf/singularity/bids-apps/fsl_6.0.3_cuda9.1.sif' 

#get preprocessed t1w and mask (e.g. from fmriprep)
in_t1w_preproc: '/project/6050199/akhanf/ext-bids/hcp_aging/bids/sub-{subject}/anat/sub-{subject}_acq-MPRvNav_T1w.nii.gz'
#in_t1w_mask: '/project/6007967/cfmm-projects/Peters/tle3T_phase2/derivatives/fmriprep_1.5.0_outputs/fmriprep/sub-{subject}/anat/sub-{subject}_desc-brain_mask.nii.gz'


#leave out extension, will grab nii.gz, bval, bvec, json
in_dwi_prefix: '/scratch/akhanf/hcp_lifespan/HCP_Aging/raw_downloads/submission_20852/HCA{subject}_V1_MR/unprocessed/Diffusion/HCA{subject}_V1_MR_dMRI_dir{acq}_{dir}'

dwi_dict:
 dir: 
  - 'AP'
  - 'PA'
 acq:
  - '98'
  - '99'


subj_dict:
 subject:   
  - '6000030'

#can use this to override bids participants.tsv - need to implement that override
participants_tsv: /path/to/participants_tsv


ants:
    dim: 3
    random_seed: 42 #requires ants version at least 2.3.1 (includes --random-seed option)
    intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
    linear:
        reg_iterations: '1000x500x250x0'
        shrink_factors: '6x4x2x1'
        smoothing_factors: '4x2x1x0'
    deform:
        shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1 
        smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0 
        reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20 
        transform_model: 'SyN[0.1,3,0]'
        sim_metric: CC
    shape_update:
        gradient_step: 0.25
