name: Tests

on:
  push:
  pull_request:


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true


  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Formatting
    steps:
    - uses: actions/checkout@v2

    - name: Test workflow
      uses: akhanf/snakebids-github-action@685b32697746727406f625f04420945eaa1e7b82
      with:
        directory: snakedwi
        snakefile: workflow/Snakefile
        args: "--dry-run"

    - name: Test report
      uses: akhanf/snakebids-github-action@685b32697746727406f625f04420945eaa1e7b82
      with:
        directory: snakedwi
        snakefile: workflow/Snakefile
        args: "--report report.zip"
